import Navigation from "@/components/navigation";
import "../styles/globals.css";

export const metadata = {
  title: "넥스트JS 첫번째 앱",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
